### ISSUE TITLE
tried to install jack on debian

### ISSUE THREAD

**Issue by lucaszanella** [SpotlightKid/python-rtmidi#1]
I've run this on debian and it tried to install with jack option

**Comment by SpotlightKid** [comment]
You ran what?

**Comment by lucaszanella** [comment]
initially I ran only python3 setup.py install but then I looked into setup.py and saw that I could insert the --no-jack argument, thank you :)

**Comment by SpotlightKid** [comment]
Ah, I see. JACK support is compiled in by default, if libjack is available on the system, yes. But compiling in JACK support doesn't hurt, because the ALSA api, if it's also compiled in, takes precedence, i.e. when you create a `MidiIn` or `MidiOut` instance without specifying the API, it will usually default to ALSA. Details are in the docstrings.

I admit that there should be a getting started documentation that covers this, though.
