### ISSUE TITLE
Virtual ports on Microsoft Windows using pytemidi

### ISSUE THREAD

**Issue by rdoursenaud** [SpotlightKid/python-rtmidi#105]
rtmidi does not support virtual ports with Microsoft Windows.

I’m pretty confident we could achieve this feature leveraging [pytemidi](https://pypi.org/project/pytemidi/) which in turn uses the excellent [VirtualMIDI](https://www.tobias-erichsen.de/software/virtualmidi.html) from Tobias Erichsen which is bundled into the popular [loopMIDI](https://www.tobias-erichsen.de/software/loopmidi.html) and [rtpMIDI](https://www.tobias-erichsen.de/software/rtpmidi.html) from the same author.

Would you be willing to accept a pull request for such a feature?

**Comment by SpotlightKid** [comment]
Hello, thanks for your suggestion, but IMO this is out of scope for `python-rtmidi`. At it's core, `python-rtmidi` is just a binding for the [RtMidi](http://www.music.mcgill.ca/~gary/rtmidi/index.html) C++ library, with only minor additions and enhancements.

The right place to add support for VirtualMIDI would thus be either be RtMidi (but development of RtMidi is slow, so that is probably difficult) or maybe via adding `pytemidi` as another backend to the Python package [mido](https://github.com/mido/mido).

**Comment by rdoursenaud** [comment]
Thanks for your reply, I also felt it was a bit out of scope hence my question.

I’ll cook something in my corner for my own use case then since `mido` is out of scope for me right now.

For the record, if anyone stumbles upon this issue, know that `RtMidi` can’t integrate `VirtualMidi` because of its license. See: https://github.com/thestk/rtmidi/issues/205
