### ISSUE TITLE
Why is MidiBase not importable?

### ISSUE THREAD

**Issue by amirteymuri** [SpotlightKid/python-rtmidi#12]
Why is the MidiBase class not have been made importable?

**Comment by SpotlightKid** [comment]
Because it is not part of the public API of the `rtmidi._rtmidi` module. Only the `MidiIn` and `MidiOut` classes and the `get_compiled_api` function and the constants are. The `MidiBase` class exists only to provide functions with a common implementation to `MidiIn`/`MidiOut` via inheritance. You should not instantiate this class itself.

Nevertheless, if you need to, you can still import it from `rtmidi_rtmidi`:

    from rtmidi._rtmidi import MidiBase
