### ISSUE TITLE
Using more than 16 channels

### ISSUE THREAD

**Issue by teymuri** [SpotlightKid/python-rtmidi#127]
Is it possible to manage more than 16 channels in rtmidi? I have a synth (Fluidsynth) that supports upto 256 channels, but don't know how to reach out to them from rtmidi. Any help is highly appreciated!

**Comment by SpotlightKid** [comment]
The limitation to 16 channels per MIDI connection is inherent to the MIDI protocol, since the channel number is encoded into the lower nibble (4 bits) of the status byte (2^4 = 16). If you need more, you need to use more ports, each with their own set of 16 channels, and distribute MIDI events between them.

**Comment by teymuri** [comment]
Do you have an example of how to manage multiple client/ports inside one `with` statement? At the moment I am using the 

```python
with clientX.open_port ...
    all_the_processing
```
paradigm.

**Comment by SpotlightKid** [comment]
The context manager (`with`) construct is only a handy way to close a port at the end of the `with` block. You don't need to use that. You can just close a port manually when you're done using it with `.close_port()`. Note that you need a separate `MidiIn` / `MidiOut` instance for each port you want to open.

**Comment by teymuri** [comment]
Great! Thanks for your help and your time!
