### ISSUE TITLE
Can't compile for kivy/android

### ISSUE THREAD

**Issue by pkor** [SpotlightKid/python-rtmidi#13]
I'm trying to include this library for use with kivy on android but keep running in to the following error when I run the recipe:
`/bin/false -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc -I/usr/include/python2.7 -c src/_rtmidi.cpp -o build/temp.linux-x86_64-2.7/src/_rtmidi.o

error: command '/bin/false' failed with exit status 1`

Any idea what this could be? Is this even a good library to use with android/ios?

**Comment by SpotlightKid** [comment]
To be honest, I have no idea, if [RtMidi](http://www.music.mcgill.ca/~gary/rtmidi/index.html), the C++ library this Python library is based on, even works on android. It may work on iOS, since, to my knowledge, iOS supports the same CoreMIDI frameworks that is used as a possible system-dependent backend for RtMidi on OS X. So as long as RtMidi and its dependencies work on the system, python-rtmidi should work too.

But since I have neither a modern Mac to compile for iOS, nor (so far) the patience to set up a built environment for Android, I can't really give a definitive answer, sorry.

I suggest you ask on the [STK mailing list](https://ccrma.stanford.edu/software/stk/maillist.html) about mobile OS support (RtAudio and RtMidi are sub-projects of STK).

**Comment by SpotlightKid** [comment]
As to your error message: it seems that distutils / setuptools has set the path of the C++ compiler to `/bin/false`, which obviously won't work. have you tried the [buildozer](https://github.com/kivy/buildozer) build environment VM from Kivy / Python4android?

**Comment by pkor** [comment]
Thanks! I am running this on the official buildozer VM from kivy. Thanks for your help. I'll look into those possibilties.
