### ISSUE TITLE
[suggestion] Please support pulseaudio

### ISSUE THREAD

**Issue by yurivict** [SpotlightKid/python-rtmidi#23]
Pulesaudio is very popular on BSD systems, and is used as a primary audio system on the FreeBSD.

**Comment by SpotlightKid** [comment]
I'm closing this ticket as invalid, because:

* RtMidi (and therefore also python-rtmidi) is solely concerned with MIDI data I/O, it doesn't handle audio data. Pulseaudio is only concerned with audio data streams, not MIDI data. AFAIK you can't use Pulseaudio for MIDI I/O.
* python-rtmidi is only a Python wrapper for the C++ library RtMidi, which implements all the OS-dependent MIDI backends (ALSA, JACK, CoreMIDI and Windows MM). Support for additional backends would have to be added to RtMidi, not python-rtmidi (only its `setup.py` would need to be changed). RtMidi is its own projects and has [its own issue tracker](https://github.com/thestk/rtmidi). You can open a ticket asking for BSD support there.

Additionally, what I gather from the very limited research I've done on this, audio and MIDI support on the different BSD flavours various greatly and documentation can be rather sketchy. FreeBSD uses Open Sounds System, which has support for MIDI on most sound cards, and sending or receiving MIDI data there usually just means writing to or reading from a device file. The closest thing to systems like Pulseaudio and JACK seems to be the [sndio](https://man.openbsd.org/sndio) framework on OpenBSD. Adding support for this to RtMidi could be worthwhile, but, as I said, this must be done in the RtMidi library, not python-rtmidi.
