### ISSUE TITLE
Question about midifilter example

### ISSUE THREAD

**Issue by luigikitten** [SpotlightKid/python-rtmidi#26]
Hi,
   (newbie here..) I have noticed that in the "midifilter" example a thread is used to process events. Is it needed?
What happens if one doesn't use a thread?
Thanks !

**Comment by SpotlightKid** [comment]
The `MidiDispatcher.run` method runs in it's own thread, so that the MIDI output is decoupled from the MIDI input callback. They communicate via a queue. The rtmidi library calls the the class instance whenever a MIDI event arrives at the MIDI input and puts it in the queue. The loop in the `run` method listens for events on that queue and filters incoming events and then outputs the resulting events. This means that even while events are sent to the MIDI output, new events can be picked up from the MIDI input and put into the queue.
