### ISSUE TITLE
Channel format

### ISSUE THREAD

**Issue by teymuri** [SpotlightKid/python-rtmidi#38]
What are the formats of the channels? And why is it not possible to assign channels with integers?

**Comment by SpotlightKid** [comment]
I'm not sure, I completely understand what your question is about, but let me explain, that this library, at its core, is only concerned with MIDI input and output. The user (developer) is responsible for passing standard-compliant MIDI data to the `MidiOut.send_message` method. For [channel voice messages](http://www.somascape.org/midi/tech/spec.html#chanmsgs) this means, that the MIDI channel is encoded in the lower four bits of the status byte. Four bits give a value range of 0 -16, i.e. channels are counted from zero. When talking about MIDI channels, though, they are usually counted from one.

So, to send a Note On message on channel 10, you'd do:

```python
note = 36
channel = 10  # counting from one here
NOTE_ON = 0x90
status = NOTE_ON | (channel - 1)  # bit-wise OR of NOTE_ON and channel (zero-based)
midiout.send_message([status, note, 127)  # full velocity
```

Since this gets tedious quickly, you can write a short wrapper method for this:

```python
class MidiOutWrapper:
    def __init__(self, midi, ch=1):
        self.channel = ch
        self._midi = midi

    def channel_message(self, command, *data, ch=None):
        """Send a MIDI channel mode message."""
        command = (command & 0xf0) | ((ch if ch else self.channel) - 1 & 0xf)
        msg = [command] + [value & 0x7f for value in data]
        self._midi.send_message(msg)
```

(The bit-wise AND operations are there to restrict values to the range 0-16 resp. 0-127.)

This allows you to send Note On message on like this:

```python
midiout = MidiOuWrapper(midiout)  # passing in a rtmidi.MidiOut instance
midiout.channel_message(NOTE_ON, 36, 127, ch=10)
midiout.channel_message(NOTE_ON, 40, 127)  # sent on default channel 1
```

You can then define further wrapper methods for frequently sent MIDI messages, e.g.:

```python
def note_off(self, note, velocity=0, ch=None):
    """Send a 'Note Off' message."""
    self.channel_message(NOTE_OFF, note, velocity, ch=ch)

def note_on(self, note, velocity=127, ch=None):
    """Send a 'Note On' message."""
    self.channel_message(NOTE_ON, note, velocity, ch=ch)

def program_change(self, program, ch=None):
    """Send a 'Program Change' message."""
    self.channel_message(PROGRAM_CHANGE, program, ch=ch)
```

an use them like this:

```python
midiout.program_change(9)  # programs counted from zero too!
midiout.note_on(36, ch=10)  # default velocity 127
midiout.note_on(40, 64)  #36  default channel 1
midiout.note_on(60)  # default velocity and channel
midiout.note_off(36, ch=10)   # default release velocity 0
midiout.note_off(40, 64)
midiout.note_off(60)
```

You can find the [midiwrapper.py](examples/advanced/midiwrapper.py) script in the `examples/advanced` folder, which has the complete code.

**Comment by teymuri** [comment]
Great! Many thanks
