### ISSUE TITLE
Update INSTALL.rst file:

### ISSUE THREAD

**Issue by magdesign** [SpotlightKid/python-rtmidi#49]
On newer Debian system you need to install the library with:

`sudo pip3 install python-rtmidi`

`sudo pip2 install python-rtmidi`

**Comment by SpotlightKid** [comment]
Added a note about this in 69ef761b2cb2a629bbacad1f12997564be178743.

I'm not showing usage of `sudo` in the install command examples, because by default `pip ` installs packages under the user's home directory now, which is preferred, IMO. If you want to install packages system-wide, use your distribution's package management.
