### ISSUE TITLE
MidiOutDummy : no functionnality

### ISSUE THREAD

**Issue by IgorDubois** [SpotlightKid/python-rtmidi#5]
Hi,

I'm trying to write a class that receives bytes messages and send them as MIDI messages, this is my __init__() function : 

`    def \__init__(self):

        self.midi_outs = [rtmidi.MidiOut(rtapi=rtmidi.API_UNSPECIFIED,name=("Midi out n"+str(n))) for n in range(0,7)]

        for i in range(0,7):

            self.midi_outs[i].open_virtual_port("Wi-MidiVPort"+str(i))

        print(self.midi_outs[0].get_port_count())
`

This is the output i get : 
`MidiOutDummy: This class provides no functionality.`
And this 8 times.

What am i doing wrong/Is that a known issue ?

**Comment by SpotlightKid** [comment]
Which operating system are you on?

Did you follow the [installation instructions](http://trac.chrisarndt.de/code/wiki/python-rtmidi/install) and did you install the requirements beforehand?

The error message indicates that python-rtmidi was compiled without support for any of the supported low-level MIDI APIs. For example, under Linux, you need the ALSA development package and, for JACK support, the JACK development package. See the section "Requirenments".

**Comment by tekhedd** [comment]
I see this behavior with Windows / Python 3.4, x64, when installing via pip. It does retrieved 0.5b1, says it "successfully installed", and then is not functional. When I try various flags, it appears to be compiling from source, so the precompiled distribution is not being found, which I suppose makes sense since all the docs reference Python 3.3. :)  I realize I may be in "it doesn't support that" territory here. 

I do have a working Cython setup with the appropriate matching compiler. (SDK 7.1) I will try a manual pull of the source and see what I can see.

**Comment by SpotlightKid** [comment]
Can you post the output of `python setup.py install` from the source dist?

Can you try a current checkout from git as well?

I haven't used my compiler set-up on Windows for a while and I need to check that it still works. I only have time for this during weekends at the moment, so it may take me some time to get to it.

**Comment by tekhedd** [comment]
I will grab the trunk code and post build results asap. My schedule is a bit thick recently (lots of gigs hooray?). I just remembered that the docs say it won't build for python x64 but we'll see about that. ;)

**Comment by SpotlightKid** [comment]
About x64: that's for Visual Studio Express. You might try with one of the newer free (for non commercial us) Visual Studio versions.

**Comment by tekhedd** [comment]
OK, here is... a lot of beautiful output. I uninstalled python_rtmidi and this is a build from a clean download of trunk. SDK 7.1 on...well I guess the build paths tell all don't they? :) It looks like a clean compile but no midi devices are found. Maybe something subtle in the platform detection?

Compiling src\_rtmidi.pyx because it changed.
[1/1] Cythonizing src\_rtmidi.pyx
running install
running bdist_egg
running egg_info
creating python_rtmidi.egg-info
writing top-level names to python_rtmidi.egg-info\top_level.txt
writing python_rtmidi.egg-info\PKG-INFO
writing dependency_links to python_rtmidi.egg-info\dependency_links.txt
writing requirements to python_rtmidi.egg-info\requires.txt
writing entry points to python_rtmidi.egg-info\entry_points.txt
writing manifest file 'python_rtmidi.egg-info\SOURCES.txt'
reading manifest file 'python_rtmidi.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '*.rst.in'
warning: no previously-included files found matching 'deploy.sh'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'python_rtmidi.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-3.4
creating build\lib.win-amd64-3.4\rtmidi
copying rtmidi\midiconstants.py -> build\lib.win-amd64-3.4\rtmidi
copying rtmidi\midiutil.py -> build\lib.win-amd64-3.4\rtmidi
copying rtmidi\release.py -> build\lib.win-amd64-3.4\rtmidi
copying rtmidi\__init__.py -> build\lib.win-amd64-3.4\rtmidi
creating build\lib.win-amd64-3.4\osc2midi
copying examples\osc2midi\device.py -> build\lib.win-amd64-3.4\osc2midi
copying examples\osc2midi\lru_cache.py -> build\lib.win-amd64-3.4\osc2midi
copying examples\osc2midi\main.py -> build\lib.win-amd64-3.4\osc2midi
copying examples\osc2midi\midievents.py -> build\lib.win-amd64-3.4\osc2midi
copying examples\osc2midi\midiio.py -> build\lib.win-amd64-3.4\osc2midi
copying examples\osc2midi\oscdispatcher.py -> build\lib.win-amd64-3.4\osc2midi
copying examples\osc2midi\__init__.py -> build\lib.win-amd64-3.4\osc2midi
running build_ext
building 'rtmidi._rtmidi' extension
creating build\temp.win-amd64-3.4
creating build\temp.win-amd64-3.4\Release
creating build\temp.win-amd64-3.4\Release\src
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc -IC:\usr\Python34\include -IC:\usr\Python34\include /Tpsrc\_rtmidi.cpp /Fobuild\temp.win-amd64-3.4\Release\src\_rtmidi.obj /EHsc
_rtmidi.cpp
src\_rtmidi.cpp(3681) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
src\_rtmidi.cpp(3682) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
src\_rtmidi.cpp(3683) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc -IC:\usr\Python34\include -IC:\usr\Python34\include /Tpsrc\RtMidi.cpp /Fobuild\temp.win-amd64-3.4\Release\src\RtMidi.obj /EHsc
RtMidi.cpp
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO "/LIBPATH:C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib" /LIBPATH:C:\usr\Python34\libs /LIBPATH:C:\usr\Python34\PCbuild\amd64 /EXPORT:PyInit__rtmidi build\temp.win-amd64-3.4\Release\src\_rtmidi.obj build\temp.win-amd64-3.4\Release\src\RtMidi.obj /OUT:build\lib.win-amd64-3.4\rtmidi\_rtmidi.pyd /IMPLIB:build\temp.win-amd64-3.4\Release\src\_rtmidi.lib /MANIFESTFILE:build\temp.win-amd64-3.4\Release\src\_rtmidi.pyd.manifest
_rtmidi.obj : warning LNK4197: export 'PyInit__rtmidi' specified multiple times; using first specification
   Creating library build\temp.win-amd64-3.4\Release\src\_rtmidi.lib and object build\temp.win-amd64-3.4\Release\src\_rtmidi.exp
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\osc2midi
copying build\lib.win-amd64-3.4\osc2midi\device.py -> build\bdist.win-amd64\egg\osc2midi
copying build\lib.win-amd64-3.4\osc2midi\lru_cache.py -> build\bdist.win-amd64\egg\osc2midi
copying build\lib.win-amd64-3.4\osc2midi\main.py -> build\bdist.win-amd64\egg\osc2midi
copying build\lib.win-amd64-3.4\osc2midi\midievents.py -> build\bdist.win-amd64\egg\osc2midi
copying build\lib.win-amd64-3.4\osc2midi\midiio.py -> build\bdist.win-amd64\egg\osc2midi
copying build\lib.win-amd64-3.4\osc2midi\oscdispatcher.py -> build\bdist.win-amd64\egg\osc2midi
copying build\lib.win-amd64-3.4\osc2midi\__init__.py -> build\bdist.win-amd64\egg\osc2midi
creating build\bdist.win-amd64\egg\rtmidi
copying build\lib.win-amd64-3.4\rtmidi\midiconstants.py -> build\bdist.win-amd64\egg\rtmidi
copying build\lib.win-amd64-3.4\rtmidi\midiutil.py -> build\bdist.win-amd64\egg\rtmidi
copying build\lib.win-amd64-3.4\rtmidi\release.py -> build\bdist.win-amd64\egg\rtmidi
copying build\lib.win-amd64-3.4\rtmidi\_rtmidi.pyd -> build\bdist.win-amd64\egg\rtmidi
copying build\lib.win-amd64-3.4\rtmidi\__init__.py -> build\bdist.win-amd64\egg\rtmidi
byte-compiling build\bdist.win-amd64\egg\osc2midi\device.py to device.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\osc2midi\lru_cache.py to lru_cache.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\osc2midi\main.py to main.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\osc2midi\midievents.py to midievents.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\osc2midi\midiio.py to midiio.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\osc2midi\oscdispatcher.py to oscdispatcher.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\osc2midi\__init__.py to __init__.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\rtmidi\midiconstants.py to midiconstants.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\rtmidi\midiutil.py to midiutil.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\rtmidi\release.py to release.cpython-34.pyc
byte-compiling build\bdist.win-amd64\egg\rtmidi\__init__.py to __init__.cpython-34.pyc
creating stub loader for rtmidi\_rtmidi.pyd
byte-compiling build\bdist.win-amd64\egg\rtmidi\_rtmidi.py to _rtmidi.cpython-34.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying python_rtmidi.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying python_rtmidi.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying python_rtmidi.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying python_rtmidi.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying python_rtmidi.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying python_rtmidi.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying python_rtmidi.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
creating dist
creating 'dist\python_rtmidi-0.6b1.dev0-py3.4-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing python_rtmidi-0.6b1.dev0-py3.4-win-amd64.egg
creating c:\usr\python34\lib\site-packages\python_rtmidi-0.6b1.dev0-py3.4-win-amd64.egg
Extracting python_rtmidi-0.6b1.dev0-py3.4-win-amd64.egg to c:\usr\python34\lib\site-packages
Adding python-rtmidi 0.6b1.dev0 to easy-install.pth file
Installing osc2midi-script.py script to C:\usr\Python34\Scripts
Installing osc2midi.exe script to C:\usr\Python34\Scripts

Installed c:\usr\python34\lib\site-packages\python_rtmidi-0.6b1.dev0-py3.4-win-amd64.egg
Processing dependencies for python-rtmidi==0.6b1.dev0
Finished processing dependencies for python-rtmidi==0.6b1.dev0

**Comment by tekhedd** [comment]
More exploration shows that only the dummy is compiled in. Clearly I need to do some magic to get the other APIs. I'll see what it takes to make this happen with SDK 7.1 as this is required for py 3.4/win.

> >>> import rtmidi
> >>> rtmidi.get_compiled_api()
> [5]

**Comment by SpotlightKid** [comment]
See PR #7.

**Comment by SpotlightKid** [comment]
Closing this, further work happens in #7.
