### ISSUE TITLE
Provide set_error_callback on MidiIn and MidiOut

### ISSUE THREAD

**Issue by rnixx** [SpotlightKid/python-rtmidi#6]
RtMidi supports setErrorCallback API on both MidiIn and MidiOut

https://www.music.mcgill.ca/~gary/rtmidi/classRtMidi.html#aa6d6f2e0d06c64268c8898aa15f3a5df

It would be nice if python-rtmidi supports it as well.

**Comment by SpotlightKid** [comment]
I hadn't noticed that this method has been added to RtMidi. Thanks for making me aware of it.

Is there any documentation on how the callback function is called, i.e. with which arguments? I guess it receives some information about the type of error that occurred? Otherwise it wouldn't be very useful?

**Comment by rnixx** [comment]
Looks like it's just a string and the optional user data.

https://github.com/thestk/rtmidi/blob/master/RtMidi.cpp#L258

**Comment by SpotlightKid** [comment]
I'll give it go when I have time, but it may be two or three weeks, as I'm rather busy at work atm.

Pull requests welcome, as always, preferably with tests, but if there's at least a good docstring, I can create those myself.
