### ISSUE TITLE
Removing old MidiOut ports from get_ports after use

### ISSUE THREAD

**Issue by PeterSR** [SpotlightKid/python-rtmidi#60]
Hi

I am working on Linux with Python 3.8 and python-rtmidi 1.4.0 and I would like to know if it is possible to remove old ports from the result of `get_ports` once they are completely done being used.

I have the following simple test program:

```python
import time
import rtmidi

from rtmidi.midiconstants import NOTE_OFF, NOTE_ON

midiout = rtmidi.MidiOut()
available_ports = midiout.get_ports()

print(available_ports)

if available_ports:
    midiout.open_port(0)
else:
    midiout.open_virtual_port("My virtual output")

with midiout:
    note_on = [NOTE_ON, 60, 60]
    note_off = [NOTE_OFF, 60, 0]
    midiout.send_message(note_on)
    time.sleep(0.5)
    midiout.send_message(note_off)
    time.sleep(0.1)

# Context manager should close it, but I wanted to be sure
midiout.close_port()

del midiout

m = rtmidi.MidiIn()
available_ports = m.get_ports()

print(available_ports)

time.sleep(100)
```

which gives the following output:

```
['Midi Through:Midi Through Port-0 14:0']
['Midi Through:Midi Through Port-0 14:0', 'RtMidiOut Client:RtMidi output 128:0']
```

Running `aconnect -i` while the Python script is sleeping at the end shows:

```
client 0: 'System' [type=kernel]
    0 'Timer           '
    1 'Announce        '
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 128: 'RtMidiOut Client' [type=user,pid=1000187]
    0 'RtMidi output   '
```

And client 128 disappears when the Python script stops.

Is there a way to remove these MidiOut devices?

Thanks!

(My use case is MIDI device discovery for a long-running application while also sending messages to some of them at the same time which interferes with the discovery)

Edit: I felt adventurous and tried to import `gc` and do `gc.collect()` before calling `get_ports` which fixes the problem. Would be nice to not have to rely on the garbage collector for this though.

**Comment by SpotlightKid** [comment]
I'm aware of the problem but I'm not sure what a good solution would be.

The problem is that with Python's `del` operator, you have no real control over when the `MidiOut` instance is actually destroyed (unless using `gc.collect()`, as you did). Only when the instance is destroyed and the [`__dealloc__` method](https://github.com/SpotlightKid/python-rtmidi/blob/e4c86d956b8f9b3e52100376969555ca2b66536f/src/_rtmidi.pyx#L1001) of the `MidiOut` extension class created in the Cython code is called, which then deletes the underlying RtMidiOut C++ class instance.

You can't call `__dealloc__` directly, neither from Python code, nor from with the `MidiOut` class itself, it is only called by Cython generated C code at instance destruction.

I could add a method to `MidiIn` and `MidiOut` to delete the C++ instances explicitly:

```py
    def __dealloc__(self):
        """De-allocate pointer to C++ class instance."""
        if hasattr(self, "thisptr"):
            del self.thisptr

    def delete(self):
        """De-allocate pointer to C++ class instance."""
        del self.thisptr
```

But if you call `delete()` on a `MidiIn` / `MidiOut` instance, you *must not* use it afterwards again, or your program will crash with a segmentation fault, which is not a behaviour I would expect from a stable library.

The only alternative I see atm is checking the existence of `thisptr` before every use, which probably has performance implications.

I'm open for netter ideas

**Comment by PeterSR** [comment]
Thank you for getting back so quickly!

Ah, I see. That is a bit of a tricky problem. I agree that none of the solutions are that elegant, but I don't necessarily know of any better ways to solve it. 

Perhaps one could "opt-in" for the performance implications by having a wrapper class that would check the pointer and only the wrapper class would be allowed to delete the pointer. Doesn't feel so pythonic though.

I will probably just keep using `gc.collect()` for now. You may close the issue if you feel like it.

**Comment by SpotlightKid** [comment]
I decided to add the `delete` method to `rtmidi.MidiIn` and `rtmidi.MidiOut` after all (92f9950 ), together with a warning in the docstring.
