### ISSUE TITLE
Output Not Working (Win10)

### ISSUE THREAD

**Issue by MasterJames** [SpotlightKid/python-rtmidi#67]
I tried running the example but nothing is being received on the device output is being sent to.
This is the code example of course
https://pypi.org/project/python-rtmidi/

I use a second device [via open_port(1)] which has no crashes like port zero  [open_port(0)] does.
rtmidi._rtmidi.SystemError: MidiOutWinMM::openPort: error creating Windows MM MIDI output port.

That is previous default port issue is apparently not functional on windows it seems. Maybe there is a deeper problem affecting the otherwise apparently working second port I have (it's an external Firewire device where the midi is working great as expected).

I am missing something? Any simple way to determine the issues cause?

**Comment by SpotlightKid** [comment]
Sorry, I am not sure whether I understand correctly what you tried to do. You ran the code example from the PyPI page, but you changed the line `midiout.open_port(0)` to `midiout.open_port(1)` because the first gave you an error?

Can you please post the full output of the error? And can you insert `print(available_ports)` on line 6 of the example and run it again and post the output here too?

Also, what MIDI device is connected to the MIDI out of the firewire interface and how are you determining that is is (not) receiving? Is the MIDI device set to receive on MIDI channel 1?

**Comment by SpotlightKid** [comment]
The output you show is clearly not from the example code shown on python-rtmidi's PyPI page. Sorry, but I can not help you, if I have to guess what you are doing exactly. Please show me the *exact* code you are running and *how* you run it.

Also, again, please tell me what receiving device is connected to your firewire interface and how it is configured (e.g. MIDI receive channel and anything else that might be important) and how yku make sure that it is indeed not receiving anything.

**Comment by SpotlightKid** [comment]
Closing this due to no further feedback. Please feel free to re-open it if you have more information.

**Comment by asigalov61** [comment]
Hey Christopher,

I am reporting the same issues with Windows/Chrome/Edge: MIDI playback does not work.

In fact, AFAIK not a single MIDI player/synth repo works right now !!! WOW!!! Can you believe this? Not a single one! The only workaround right now is to use this code:

```
!pip install pyFluidSynth
!apt install fluidsynth #Pip does not work for some reason. Only apt works
!pip install midi2audio

!cp /usr/share/sounds/sf2/FluidR3_GM.sf2 /content/font.sf2

from midi2audio import FluidSynth
from google.colab import output
from IPython.display import display, Javascript, HTML, Audio

FluidSynth("/content/font.sf2").midi_to_audio('output_midi.mid','output_wav.wav')
# set the src and play
Audio("output_wav.wav")
```
So if you can look into it and fix it somehow, it will be appreciated by everyone in the open-source community, and by myself, in particular, because we do need at least 1 properly working MIDI player/synthesizer.

Otherwise, great job on Python-RtMidi. Thank you :))

Alex

**Comment by asigalov61** [comment]
This is the error message that I get with RtMidi code, no matter what I try:

RuntimeError                              Traceback (most recent call last)
src/_rtmidi.pyx in rtmidi._rtmidi.MidiOut.__cinit__()

RuntimeError: MidiOutAlsa::initialize: error creating ALSA sequencer client object.

During handling of the above exception, another exception occurred:

SystemError                               Traceback (most recent call last)
<ipython-input-1-2cf96645e5ed> in <module>()
      3 import rtmidi
      4 
----> 5 midiout = rtmidi.MidiOut()
      6 available_ports = midiout.get_ports()
      7 

src/_rtmidi.pyx in rtmidi._rtmidi.MidiOut.__cinit__()

SystemError: MidiOutAlsa::initialize: error creating ALSA sequencer client object.

**Comment by SpotlightKid** [comment]
Please do not re-use old issues for unrelated problems.

You first mention problems with Windows, but then show an error message, which is related to ALSA, thus Linux.

Please open a new issue and specify exactly, which code you were trying to run, how you ran it and where (i.e OS, Python version, etc.).
