### ISSUE TITLE
Is the documentation outdated?

### ISSUE THREAD

**Issue by alifeinbinary** [SpotlightKid/python-rtmidi#75]
Hello! I'm noticing that a lot of references in the available documentation no longer apply. I'm relying heavily on using help(rtmidi) to determine syntax and function names but I'm still coming to dead-ends where I can't determine what arguments to provide. For example: `count = rtmidi.RtMidiIn.getPortCount()` throws an error saying that an argument is required but consulting the rtmidi documentation, that doesn't seem to be necessary to get a count returned. 

Did you make a major update to the codebase but the documentation is lagging behind? Any idea when an updated version might arrive? I could help, I'm familiar with the older version of the library.

**Comment by SpotlightKid** [comment]
No, I didn't change anything about the API or the documentation recently. I'm wondering, to which documentation you refer, since the [python-rtmidi documention](https://spotlightkid.github.io/python-rtmidi/rtmidi.html#module-rtmidi) clearly describes the API and when you'll read it, you'll notice that the names of the wrappers for the C++ functions/methods have all been adapted to the `lower_case_with_underscores` paradigm, which is usually used in Python.

The README also mentions this:

> The API is basically the same as the C++ one but with the naming scheme of classes, methods and parameters adapted to the Python PEP-8 conventions and requirements of the Python package naming structure.

Please note that `rtmidi.RtMidiIn.get_port_count` is not a static method, i.e. you need to create an instance of `rtmidi.RtMidiIn` and call the method on that instance:

    import rtmidi
    midiin = rtmidi.MidiIn()
    num_ports = midiin.get_port_count()

**Comment by SpotlightKid** [comment]
Closing this due to no further feedback.
